theme: jekyll-theme-minimal
title: [MSCraft]
description: [Official webpage for MSCraft, the official Minecraft server for the MSC Discord server.]
logo: [https://raw.githubusercontent.com/MSCraftWiki/mscraft.org/main/assets/img/logo.png]